"""
PetConnect AI — LLM Health Symptom Triage Assistant
Processes natural language symptom descriptions and outputs structured medical risk triage recommendations.
"""

class LLMHealthAssistant:
    def __init__(self):
        self.emergency_keywords = ["vomit", "blood", "collapse", "seizure", "choking", "poison", "hit by car"]
        self.moderate_keywords = ["not eating", "appetite", "scratching", "diarrhea", "limping", "lethargic"]

    def triage_symptom(self, user_query: str) -> dict:
        query_lower = user_query.lower()
        
        # Check emergency triggers
        for kw in self.emergency_keywords:
            if kw in query_lower:
                return {
                    "severity": "CRITICAL_EMERGENCY",
                    "triage_color": "#EF4444",
                    "advice": "⚠️ CRITICAL MEDICAL WARNING: The symptoms reported suggest a potential veterinary emergency. Transport your pet to the nearest 24/7 veterinary clinic immediately.",
                    "recommended_action": "Dispatch Emergency SOS Alert",
                    "disclaimer": "This AI triage output is generated by LLM heuristics and does not replace in-person veterinary treatment."
                }
                
        # Check moderate triggers
        for kw in self.moderate_keywords:
            if kw in query_lower:
                return {
                    "severity": "MODERATE_ATTENTION",
                    "triage_color": "#F59E0B",
                    "advice": "The symptoms reported (e.g. appetite changes or localized irritation) warrant careful monitoring. Ensure fresh water is accessible and observe for 12–24 hours.",
                    "recommended_action": "Schedule Non-Emergency Vet Appointment if symptoms persist past 24 hours.",
                    "disclaimer": "This AI triage output is generated by LLM heuristics and does not replace in-person veterinary treatment."
                }

        # Default low risk response
        return {
            "severity": "LOW_RISK",
            "triage_color": "#10B981",
            "advice": "No immediate critical flags detected from the description. Keep your pet rested, hydrated, and maintain normal routine.",
            "recommended_action": "Routine Health Log Entry",
            "disclaimer": "This AI triage output is generated by LLM heuristics and does not replace in-person veterinary treatment."
        }

if __name__ == "__main__":
    assistant = LLMHealthAssistant()
    print("Testing LLM Assistant:")
    print(assistant.triage_symptom("My dog is vomiting blood"))
